ALTER TABLE users
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER';

UPDATE users
SET role = CASE WHEN is_admin THEN 'ADMIN' ELSE 'CUSTOMER' END
WHERE is_admin IS NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT users_role_check CHECK (role IN ('CUSTOMER', 'ADMIN'));

ALTER TABLE users
    DROP COLUMN IF EXISTS is_admin;
